/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Config.ConnectionManager;
import com.JDBC.JDBCManager;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javafx.scene.control.Alert;
import javafx.scene.control.CheckBox;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;

/**
 *
 * @author FURIOUS
 */
public class OpenProject extends AbstractFrame {

    JPanel pnlCheckbox = new JPanel();
    static String[] users = null;
    static JRadioButton[] rdoSelectProject = null;
    static ArrayList<String> tempSelectedProjectName = new ArrayList<>();
    static long tempSelectedProjectId = 0;
    static int selectedRadioIndex = 0;
    static String selectedProjectName = "";
    static ArrayList<HashMap<String, String>> al;

    /**
     * Creates new form SelectGamePlayerRegistrationForm
     */
    public OpenProject() {
        initComponents();

        JFrame frame = this;
        JDBCManager manager = ConnectionManager.getConnection();
        String sql = "select * from project where`userEmail` = '" + LogInForm.getCurrentSessionUser().getEmail() + "';";
        System.err.println(LogInForm.getCurrentSessionUser().getEmail());
        //Copied code
        al = manager.getQueryData(sql);
//        for(int x = 0; x<al.size(); x++){
//            for(int y = 0; y<al.get(x).size(); y++){
//                System.out.println(al.get(x).get("projectName")+" "+al.get(x).get("projectId"));
//            }
//        }
        int size = al.size();
        users = new String[size];
        pnlCheckbox.setLayout(new GridLayout(size, 1, 0, 2));
        JButton btnOpen = this.btnAdd;
        rdoSelectProject = new JRadioButton[size];
        for (int i = 0; i < size; i++) {
            rdoSelectProject[i] = new JRadioButton();
            selectedRadioIndex = i;
            rdoSelectProject[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    JRadioButton rdo = (JRadioButton) ae.getSource();
                    for (int p = 0; p < size; p++) {
                        if (rdoSelectProject[p].isSelected()) {
                            rdoSelectProject[p].setSelected(false);
                        }
                    }
                    rdo.setSelected(true);
                }
            });

            rdoSelectProject[i].setText(al.get(i).get("projectName"));
            pnlCheckbox.add(rdoSelectProject[i]);
            for (int j = 0; j < tempSelectedProjectName.size(); j++) {
                if (rdoSelectProject[i].getText().equals(tempSelectedProjectName.get(j))) {
                    rdoSelectProject[i].setSelected(true);
                    break;
                }
            }
        }

        frame.setDefaultCloseOperation(2);
        btnOpen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e
            ) {
                tempSelectedProjectName.clear();
                tempSelectedProjectId = 0;
                int size = rdoSelectProject.length;
                for (int i = 0, j = 0; i < size; i++) {
//                    rdoSelectProject[i].setSelected(false);
                    if (rdoSelectProject[i].isSelected() == true) {
                        selectedProjectName = rdoSelectProject[i].getText();
                        tempSelectedProjectId = Long.parseLong(al.get(i).get("projectId"));
                        users[j++] = al.get(i).get("projectId");
                    }
                }
                if (tempSelectedProjectId != 0) {
                    frame.dispose();

                    ShowPhasesInProject phasesInProject = new ShowPhasesInProject(tempSelectedProjectId);
                    System.out.println(tempSelectedProjectId);
                    phasesInProject.setVisible(true);
                } else {
                    Main.showMessageDialog(Alert.AlertType.ERROR, "Error", null, "No project exists.");
                }

            }
        });

        btnClose.addActionListener(
                new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e
            ) {
                frame.dispose();

            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpn = new javax.swing.JScrollPane(pnlCheckbox);
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        btnAdd.setBackground(new java.awt.Color(51, 102, 255));
        btnAdd.setText("Open Project");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setText("Close");

        jLabel1.setText("Please select a project to open");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpn)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scpn;
    // End of variables declaration//GEN-END:variables
}
